In [2]:
import os
import torch

pinn_train = True
kan_train = False
n_layer = 5
layer_idx = 0
optim = "Adam"
lr = "5e-3"
epoch = 1000

In [7]:
pdt_dir = f"./output/sep-find-pde/pinn-{n_layer}layers-li{layer_idx}-opt{optim}-lr{lr}-ep{epoch}"
pdt = torch.load(os.path.join(pdt_dir, "PDTs.pt"), map_location="cpu")
pdt

[tensor([ 0.0020,  0.0020,  0.0031,  ..., -0.8846,  0.0191,  0.0191],
        requires_grad=True),
 tensor([ 0.0058,  0.0058,  0.0085,  ..., -0.5350,  0.0055,  0.0055],
        requires_grad=True),
 tensor([0., 0., 0.,  ..., 0., 0., 0.], requires_grad=True)]

In [8]:
lr = "3e-3"
pdt_dir = f"./output/sep-find-pde/pinn-{n_layer}layers-li{layer_idx}-opt{optim}-lr{lr}-ep{epoch}"
pdt = torch.load(os.path.join(pdt_dir, "PDTs.pt"), map_location="cpu")
pdt

[tensor([ 0.0660, -0.0192,  0.0030,  ..., -0.6512, -0.0078, -0.0078],
        requires_grad=True),
 tensor([-0.0456, -0.0686, -0.0574,  ...,  0.0258, -0.0014, -0.0014],
        requires_grad=True),
 tensor([0., 0., 0.,  ..., 0., 0., 0.], requires_grad=True)]

In [3]:
lr = "5e-3"
epoch = 5000
pdt_dir = f"./output/sep-find-pde/pinn-{n_layer}layers-li{layer_idx}-opt{optim}-lr{lr}-ep{epoch}"
pdt = torch.load(os.path.join(pdt_dir, "PDTs.pt"), map_location="cpu")
pdt

[tensor([0.0104, 0.0104, 0.0092,  ..., 0.1066, 0.0000, 0.0000],
        requires_grad=True),
 tensor([-0.0060, -0.0060, -0.0051,  ...,  0.1083,  0.0000,  0.0000],
        requires_grad=True),
 tensor([0., 0., 0.,  ..., 0., 0., 0.], requires_grad=True)]